services:
  thedevway-gpt:
    image: ghcr.io/open-webui/open-webui:main
    container_name: thedevway-gpt
    volumes:
      - ./thedevway-gpt:/app/backend/data
    ports:
      - 127.0.0.1:3000:8080
    environment:
      - 'WEBUI_SECRET_KEY='
    restart: always
  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    volumes:
      - ./thedevway-gpt/pipelines:/app/pipelines
    ports:
      - 127.0.0.1:9099:9099
    restart: always
networks:
  gpt:
    internal: true
